### ISSUE TITLE
How do I put my existing django app

### ISSUE THREAD

**Issue by RadZaeem** [rokups/hello-vue-django#3]
The folder structure is different -- seems that project and app dir are merged.

Any toy example like Django polls or Todo app with this boilerplate?

**Comment by rokups** [comment]
Unmerging is easy though. All you need to do is:

1. Create your app folder, lets call it `myapp`.
2. Replace [this](https://github.com/rokups/hello-vue-django/blob/master/backend/settings.py#L39) with `myapp`.
3. Move [views.py](https://github.com/rokups/hello-vue-django/blob/master/backend/views.py) to `myapp` folder.

If you wish to add more apps all you need to do is:

1. Create top level folder `otherapp`.
2. Add `otherapp` to [settings.py](https://github.com/rokups/hello-vue-django/blob/master/backend/settings.py#L39).

If you wish to use anything installed via pip, say `allauth`, all you need to do is follow instructions on project's website detailing how to update `settings.py`.
