### ISSUE TITLE
How to pass data？example: view.py  =>  => App.vue

### ISSUE THREAD

**Issue by zaxlct** [rokups/hello-vue-django#4]
Thank you for your project, which is very helpful to me

I have a problem:

```python
def index(request):
    return render(request, 'index.html', {
        'test': 123
    })
```
In App.vue, What should I do to use this object for test?
I tried to do that, but failed
```html
<div>{test}</div>
```

Can App.vue get data only through AJAX?

**Comment by rokups** [comment]
Yes, you should use ajax.
