### ISSUE TITLE
CSRF verification failed. Post request aborted.

### ISSUE THREAD

**Issue by zaxlct** [rokups/hello-vue-django#5]
In App.vue, I encountered a problem when I sent a post request through AJAX.
The browser prompts me that 'CSRF verification failed. Request aborted.'
Status Code:403 Forbidden

How to solve this problem? 
Thank you

**Comment by rokups** [comment]
CSRF token is served in a cookie afaik. You may use javascript to get CSRF value from a cookie and use it in your ajax request.

**Comment by zaxlct** [comment]
> CSRF token is served in a cookie afaik. You may use javascript to get CSRF value from a cookie and use it in your ajax request.



thank you
